### ISSUE TITLE
disabling IPv6 for ICE

### ISSUE THREAD

**Issue by 459below** [jitsi/jitsi-android#36]
Although it'll be a few years until we will have full IPv6 connectivity, Recent Android Versions are very eager to use IPv6 anywhere they can. This seems to be a major problem in getting a proper peer-to-peer connection going to an IPv4 contact. Rooted devices can use `echo "1" > /proc/sys/net/ipv6/conf/wlan0/disable_ipv6` to temporary disable it. But I am very certain that most of the people do not have IPv6 connectivity and it should become a bigger problem the more people will get it, before it will become less of an issue again.

**Comment by mondain** [comment]
In ice4j, it's easy enough to simply ignore the candidates which contain the xxxx:xxxx:* pattern; that's what I did in my app.

**Comment by mondain** [comment]
Another thing to try is to pass the googIPv6:false option in your peer connection.

**Comment by 459below** [comment]
Thanks for the pointers. I'm not yet familiar with ICE or WebRTC, but I will try to find the appropriate lines to set this.

**Comment by bgrozev** [comment]
@459below setting this property will disable ipv6 in ice4j (the ICE library used in jitsi-android):
org.ice4j.ipv6.DISABLED=true

**Comment by mondain** [comment]
@bgrozev Is there a wiki page or doc somewhere that lists the system props available for the jitsi projects? Especially in this case ice4j?

**Comment by bgrozev** [comment]
Unfortunately not.
