### ISSUE TITLE
What are future plans for this project?

### ISSUE THREAD

**Issue by milosjovac** [jitsi/jitsi-android#44]
Hi all,

I'm interested in faith of jitsi for Android. It states at roadmap at jitsi.org(https://jitsi.org/Development/Roadmap) that Android development is currently on hold, and last commits including code manipulation are almost one year old. Any plans on moving project to the Gradle, or continuing the development?

**Comment by Bugsbane** [comment]
Yes, I'm very curious, too. Currently there only seems to be [one open source android app that can do video chat](https://github.com/QuickBlox/q-municate-android/notifications) as far as I can see, which doesn't seem to be run in a particularly community run way.

Jitsi is one of the few desktop apps that has any success and mindshare in this area, so it would be great to see it extend to mobile, too.

**Comment by ibauersachs** [comment]
There are no further plans for the time being. Community contributions or development would be appreciated.
If there is active development going on, we might be able to provide automated builds again.

**Comment by cmeng-git** [comment]
I have started a new development on aTalk application – a fork from the jisti-android.  If you are interested, you may download the apk from the following site.

download_link=http://atalk.sytes.net/releases/atalk-android/aTalk-release.apk

**Comment by puchrojo** [comment]
OK, but wo are the github clone from aTalk?

**Comment by bugmenot2** [comment]
You can check for updated forks here: https://github.com/jitsi/jitsi-android/network
