### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by narcisgarcia** [jitsi/jitsi-android#61]
Is Jitsi-Android same application as "Jitsi meet" or "Jitsi desktop" ?
Downloading some of those, can I get Jitsi application?

...or how to download APK without Google?

**Comment by saghul** [comment]
This repository was a mobile equivalent to Jitsi Desktop, but it's currently unmaintained. The Jitsi Meet web app and the mobile client live in the "jitsi-meet" repository. If you want an apk for that, you can get it via Google Play or any of the widely available apk mirrors.
